### ISSUE TITLE
CONTRIBUTING.md update request

### ISSUE THREAD

**Issue by jim4067** [reactdeveloperske/Fantastic-Frontend-React#13]
in the contributing guidlines, It is advised to comment on an issue to work on or create a new one if it does not exist to have a large chance of it getting merged. 

Is it possible to update this line? I do not want to have to create an issue, then have to create a PR for it when I can create a description of what my PR does in the description text-box? 

Also, when making small changes, for-example typos, this becomes quite cumbersome to do.

Sincerely,
your friendly neighborhood developer.

**Comment by stephanieopala** [comment]
Hello @jim4067 Thanks for your suggestion. However, we highly recommend creating an issue or asking to be assigned an issue before making a pull request.

**Comment by jim4067** [comment]
thanks 👍🏾
