### ISSUE TITLE
Add up-to date React-Native Tutorials and Learning resources.

### ISSUE THREAD

**Issue by david-mbugua** [reactdeveloperske/Fantastic-Frontend-React#15]
The learning tutorials provided are great, though we could also add more resources to help developers who want to learn React Native in particular.

**Comment by orama254** [comment]
Hello @david-mbugua 

This is a good suggestion, feel free to contribute. remember to follow the provided [Contribution Guidelines](https://github.com/reactdeveloperske/Fantastic-Frontend-React/blob/main/CONTRIBUTING.md)
