### ISSUE TITLE
Categorize the resources into: Beginner, Intermediate, Advanced 

### ISSUE THREAD

**Issue by King-Kingah** [reactdeveloperske/Fantastic-Frontend-React#8]
I suggest that the resources be placed in categories for easier learning into beginner, intermediate and advanced. For instance, there can be an extra column for the adds the level label or tag or create different tables for each level.

**Comment by stephanieopala** [comment]
Hello @King-Kingah thanks for the suggestion. Would you like to do it?

**Comment by stephanieopala** [comment]
Issue approved.

**Comment by King-Kingah** [comment]
Thank you @stephanieopala .

**Comment by stephanieopala** [comment]
Hello @King-Kingah are you still working on this issue?

**Comment by King-Kingah** [comment]
> Hello @King-Kingah are you still working on this issue?

Yes, I'm working on it.

**Comment by King-Kingah** [comment]
Hello @stephanieopala , I've given it some thought, and it would require the contributor to first study or go through the course/tutorial especially for those that are not explicitly noted as beginner or advanced etc.

**Comment by stephanieopala** [comment]
@King-Kingah Okay. So do you want to go ahead with it or anyone else can take it up?

**Comment by King-Kingah** [comment]
> @King-Kingah Okay. So do you want to go ahead with it or anyone else can take it up?

I just wanted to alert you on that. I'll gladly proceed if you're okay with it.

**Comment by stephanieopala** [comment]
> > @King-Kingah Okay. So do you want to go ahead with it or anyone else can take it up?
> 
> I just wanted to alert you on that. I'll gladly proceed if you're okay with it.

Alright, that's fine.
